[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/zoho/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/token/*"
  to = "/.netlify/functions/proxy"
  status = 200
