export const NAV_LINKS = [
  {
    name: 'Home',
    url: '/',
  },
  // {
  //   name: 'Properties',
  //   url: '/properties',
  // },
  // {
  //   name: 'About Us',
  //   url: '/about',
  // },
  // {
  //   name: 'Careers',
  //   url: '/careers',
  // },
]

const BANGALORE_AREAS = [
  "KR Puram",
  "Anekal",
  "Begur",
  "Kamakshipalya",
  "Chikkaballapura",
  "Kengeri",
  "Hanumanthanagar",
  "Bellandur",
  "CV Raman Nagar",
  "Hoodi",
  "Mahadevapura",
  "Marathahalli",
  "Varthur",
  "Whitefield",
  "Banaswadi",
  "HBR Layout",
  "Horamavu",
  "Kalyan Nagar",
  "Kammanahalli",
  "Lingarajapuram",
  "Ramamurthy Nagar",
  "Hebbal",
  "Jalahalli",
  "Mathikere",
  "Peenya",
  "Vidyaranyapura",
  "Yelahanka",
  "Yeshwanthpur",
  "Bommanahalli",
  "Bommasandra",
  "BTM Layout",
  "Electronic City",
  "HSR Layout",
  "Koramangala",
  "Madiwala",
  "Banashankari",
  "Basavanagudi",
  "Girinagar",
  "JP Nagar",
  "Jayanagar",
  "Kumaraswamy Layout",
  "Padmanabhanagar",
  "Uttarahalli",
  "Basaveshwaranagar",
  "Kamakshipalya",
  "Mahalakshmi Layout",
  "Nagarbhavi",
  "Nandini Layout",
  "Nayandahalli",
  "Rajajinagar",
  "Rajarajeshwari Nagar",
  "Vijayanagar",
  "Attibele",
  "Chandapura",
  "Thavarekere",
  "Chikkabanavara",
  "Hesaraghatta",
  "Jigani",
  "Nelamangala",
  "Sarjapura"
];
