export const NAV_LINKS = [
  {
    name: 'Home',
    id: "home",
    url: '/',
  }, {
    name: "About",
    id: "about"
  }, {
    name: "Why Choose Us",
    id: "why-us"
  }, {
    name: "How It Works",
    id: "process"
  }, {
    name: "FAQs",
    id: "faq"
  }, {
    name: "Contact Us",
    id: "contact"
  }
  // {
  //   name: 'Properties',
  //   url: '/properties',
  // },
  // {
  //   name: 'About Us',
  //   url: '/about',
  // },
  // {
  //   name: 'Careers',
  //   url: '/careers',
  // },
]

export const PROPERTY_TYPES = [
  {
    label: 'Land',
    value: 'Land',
  },
  {
    label: 'Land And Building',
    value: 'Land And Building',
  },
  {
    label: 'Flat',
    value: 'Flat',
  },
  {
    label: 'House',
    value: 'House',
  },
  {
    label: 'Plot',
    value: 'Plot',
  },
]

export const STATES = [
  { value: 'Karnataka', label: 'Karnataka' },
  { value: 'Tamil Nadu', label: 'Tamil Nadu' },
]

export const CITIES = [
  // Karnataka cities
  { value: 'Bengaluru', label: 'Bengaluru', state: 'Karnataka' },
  { value: 'Bagalkot', label: 'Bagalkot', state: 'Karnataka' },
  { value: 'Ballari', label: 'Ballari', state: 'Karnataka' },
  { value: 'Belagavi', label: 'Belagavi', state: 'Karnataka' },
  { value: 'Bidar', label: 'Bidar', state: 'Karnataka' },
  { value: 'Chamarajanagar', label: 'Chamarajanagar', state: 'Karnataka' },
  { value: 'Chikkaballapur', label: 'Chikkaballapur', state: 'Karnataka' },
  { value: 'Chikkamagaluru', label: 'Chikkamagaluru', state: 'Karnataka' },
  { value: 'Chitradurga', label: 'Chitradurga', state: 'Karnataka' },
  { value: 'Dakshina Kannada', label: 'Dakshina Kannada', state: 'Karnataka' },
  { value: 'Davanagere', label: 'Davanagere', state: 'Karnataka' },
  { value: 'Dharwad', label: 'Dharwad', state: 'Karnataka' },
  { value: 'Gadag', label: 'Gadag', state: 'Karnataka' },
  { value: 'Hassan', label: 'Hassan', state: 'Karnataka' },
  { value: 'Haveri', label: 'Haveri', state: 'Karnataka' },
  { value: 'Kalaburagi', label: 'Kalaburagi', state: 'Karnataka' },
  { value: 'Kodagu', label: 'Kodagu', state: 'Karnataka' },
  { value: 'Kolar', label: 'Kolar', state: 'Karnataka' },
  { value: 'Koppal', label: 'Koppal', state: 'Karnataka' },
  { value: 'Mandya', label: 'Mandya', state: 'Karnataka' },
  { value: 'Mysuru', label: 'Mysuru', state: 'Karnataka' },
  { value: 'Raichur', label: 'Raichur', state: 'Karnataka' },
  { value: 'Ramanagara', label: 'Ramanagara', state: 'Karnataka' },
  { value: 'Shivamogga', label: 'Shivamogga', state: 'Karnataka' },
  { value: 'Tumakuru', label: 'Tumakuru', state: 'Karnataka' },
  { value: 'Udupi', label: 'Udupi', state: 'Karnataka' },
  { value: 'Uttara Kannada', label: 'Uttara Kannada', state: 'Karnataka' },
  { value: 'Vijayapura', label: 'Vijayapura', state: 'Karnataka' },
  { value: 'Yadgir', label: 'Yadgir', state: 'Karnataka' },
  { value: 'Vijayanagara', label: 'Vijayanagara', state: 'Karnataka' },

  // Tamil Nadu cities
  { value: 'Chennai', label: 'Chennai', state: 'Tamil Nadu' },
  { value: 'Coimbatore', label: 'Coimbatore', state: 'Tamil Nadu' },
  { value: 'Madurai', label: 'Madurai', state: 'Tamil Nadu' },
  { value: 'Tiruchirappalli', label: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { value: 'Salem', label: 'Salem', state: 'Tamil Nadu' },
  { value: 'Tirunelveli', label: 'Tirunelveli', state: 'Tamil Nadu' },
  { value: 'Tiruppur', label: 'Tiruppur', state: 'Tamil Nadu' },
  { value: 'Erode', label: 'Erode', state: 'Tamil Nadu' },
  { value: 'Vellore', label: 'Vellore', state: 'Tamil Nadu' },
  { value: 'Thoothukudi', label: 'Thoothukudi', state: 'Tamil Nadu' },
  { value: 'Dindigul', label: 'Dindigul', state: 'Tamil Nadu' },
  { value: 'Thanjavur', label: 'Thanjavur', state: 'Tamil Nadu' },
  { value: 'Ranipet', label: 'Ranipet', state: 'Tamil Nadu' },
  { value: 'Sivakasi', label: 'Sivakasi', state: 'Tamil Nadu' },
  { value: 'Karur', label: 'Karur', state: 'Tamil Nadu' },
  { value: 'Udhagamandalam', label: 'Udhagamandalam', state: 'Tamil Nadu' },
  { value: 'Hosur', label: 'Hosur', state: 'Tamil Nadu' },
  { value: 'Nagercoil', label: 'Nagercoil', state: 'Tamil Nadu' },
  { value: 'Kanchipuram', label: 'Kanchipuram', state: 'Tamil Nadu' },
  { value: 'Cuddalore', label: 'Cuddalore', state: 'Tamil Nadu' },
  { value: 'Kumbakonam', label: 'Kumbakonam', state: 'Tamil Nadu' },
  { value: 'Tiruvannamalai', label: 'Tiruvannamalai', state: 'Tamil Nadu' },
  { value: 'Pollachi', label: 'Pollachi', state: 'Tamil Nadu' },
  { value: 'Rajapalayam', label: 'Rajapalayam', state: 'Tamil Nadu' },
  { value: 'Sivaganga', label: 'Sivaganga', state: 'Tamil Nadu' },
  { value: 'Pudukkottai', label: 'Pudukkottai', state: 'Tamil Nadu' },
  { value: 'Vaniyambadi', label: 'Vaniyambadi', state: 'Tamil Nadu' },
  { value: 'Theni', label: 'Theni', state: 'Tamil Nadu' },
  { value: 'Nagapattinam', label: 'Nagapattinam', state: 'Tamil Nadu' },
  { value: 'Gudiyatham', label: 'Gudiyatham', state: 'Tamil Nadu' },
  { value: 'Krishnagiri', label: 'Krishnagiri', state: 'Tamil Nadu' },
  { value: 'Dharmapuri', label: 'Dharmapuri', state: 'Tamil Nadu' },
  { value: 'Tuticorin', label: 'Tuticorin', state: 'Tamil Nadu' },
  { value: 'Ariyalur', label: 'Ariyalur', state: 'Tamil Nadu' },
  { value: 'Chengalpattu', label: 'Chengalpattu', state: 'Tamil Nadu' },
  { value: 'Kallakurichi', label: 'Kallakurichi', state: 'Tamil Nadu' },
  { value: 'Kanyakumari', label: 'Kanyakumari', state: 'Tamil Nadu' },
  { value: 'Namakkal', label: 'Namakkal', state: 'Tamil Nadu' },
  { value: 'Mayiladuthurai', label: 'Mayiladuthurai', state: 'Tamil Nadu' },
  { value: 'Perambalur', label: 'Perambalur', state: 'Tamil Nadu' },
  { value: 'Ramanathapuram', label: 'Ramanathapuram', state: 'Tamil Nadu' },
  { value: 'Tenkasi', label: 'Tenkasi', state: 'Tamil Nadu' },
  { value: 'Thiruvallur', label: 'Thiruvallur', state: 'Tamil Nadu' },
  { value: 'Thiruvarur', label: 'Thiruvarur', state: 'Tamil Nadu' },
  { value: 'Tirupathur', label: 'Tirupathur', state: 'Tamil Nadu' },
  { value: 'Viluppuram', label: 'Viluppuram', state: 'Tamil Nadu' },
  { value: 'Virudhunagar', label: 'Virudhunagar', state: 'Tamil Nadu' }

]

export const BANGALORE_AREAS = [
  { value: 'KR Puram', label: 'KR Puram' },
  { value: 'Anekal', label: 'Anekal' },
  { value: 'Begur', label: 'Begur' },
  { value: 'Chikkaballapura', label: 'Chikkaballapura' },
  { value: 'Kengeri', label: 'Kengeri' },
  { value: 'Hanumanthanagar', label: 'Hanumanthanagar' },
  { value: 'Bellandur', label: 'Bellandur' },
  { value: 'CV Raman Nagar', label: 'CV Raman Nagar' },
  { value: 'Hoodi', label: 'Hoodi' },
  { value: 'Mahadevapura', label: 'Mahadevapura' },
  { value: 'Marathahalli', label: 'Marathahalli' },
  { value: 'Varthur', label: 'Varthur' },
  { value: 'Whitefield', label: 'Whitefield' },
  { value: 'Banaswadi', label: 'Banaswadi' },
  { value: 'HBR Layout', label: 'HBR Layout' },
  { value: 'Horamavu', label: 'Horamavu' },
  { value: 'Kalyan Nagar', label: 'Kalyan Nagar' },
  { value: 'Kammanahalli', label: 'Kammanahalli' },
  { value: 'Lingarajapuram', label: 'Lingarajapuram' },
  { value: 'Ramamurthy Nagar', label: 'Ramamurthy Nagar' },
  { value: 'Hebbal', label: 'Hebbal' },
  { value: 'Jalahalli', label: 'Jalahalli' },
  { value: 'Mathikere', label: 'Mathikere' },
  { value: 'Peenya', label: 'Peenya' },
  { value: 'Vidyaranyapura', label: 'Vidyaranyapura' },
  { value: 'Yelahanka', label: 'Yelahanka' },
  { value: 'Yeshwanthpur', label: 'Yeshwanthpur' },
  { value: 'Bommanahalli', label: 'Bommanahalli' },
  { value: 'Bommasandra', label: 'Bommasandra' },
  { value: 'BTM Layout', label: 'BTM Layout' },
  { value: 'Electronic City', label: 'Electronic City' },
  { value: 'HSR Layout', label: 'HSR Layout' },
  { value: 'Koramangala', label: 'Koramangala' },
  { value: 'Madiwala', label: 'Madiwala' },
  { value: 'Banashankari', label: 'Banashankari' },
  { value: 'Basavanagudi', label: 'Basavanagudi' },
  { value: 'Girinagar', label: 'Girinagar' },
  { value: 'JP Nagar', label: 'JP Nagar' },
  { value: 'Jayanagar', label: 'Jayanagar' },
  { value: 'Kumaraswamy Layout', label: 'Kumaraswamy Layout' },
  { value: 'Padmanabhanagar', label: 'Padmanabhanagar' },
  { value: 'Uttarahalli', label: 'Uttarahalli' },
  { value: 'Basaveshwaranagar', label: 'Basaveshwaranagar' },
  { value: 'Kamakshipalya', label: 'Kamakshipalya' },
  { value: 'Mahalakshmi Layout', label: 'Mahalakshmi Layout' },
  { value: 'Nagarbhavi', label: 'Nagarbhavi' },
  { value: 'Nandini Layout', label: 'Nandini Layout' },
  { value: 'Nayandahalli', label: 'Nayandahalli' },
  { value: 'Rajajinagar', label: 'Rajajinagar' },
  { value: 'Dasanapura', label: 'Dasanapura' },
  { value: 'Kalaburgi', label: 'Kalaburgi' },
  { value: 'Rajarajeshwari Nagar', label: 'Rajarajeshwari Nagar' },
  { value: 'Vijayanagar', label: 'Vijayanagar' },
  { value: 'Attibele', label: 'Attibele' },
  { value: 'Chandapura', label: 'Chandapura' },
  { value: 'Thavarekere', label: 'Thavarekere' },
  { value: 'Chikkabanavara', label: 'Chikkabanavara' },
  { value: 'Hesaraghatta', label: 'Hesaraghatta' },
  { value: 'Jigani', label: 'Jigani' },
  { value: 'Nelamangala', label: 'Nelamangala' },
  { value: 'Sarjapura', label: 'Sarjapura' },
  // Missing areas added:
  { value: 'Bagalur', label: 'Bagalur' },
  { value: 'Bannerghatta', label: 'Bannerghatta' },
  // { value: 'Belagavi', label: 'Belagavi' },
  { value: 'Bidarahalli', label: 'Bidarahalli' },
  { value: 'Cooke Town', label: 'Cooke Town' },
  { value: 'Cunningham Road', label: 'Cunningham Road' },
  { value: 'Devanahalli', label: 'Devanahalli' },
  { value: 'Doddanekundi', label: 'Doddanekundi' },
  { value: 'Doddaballapura', label: 'Doddaballapura' },
  { value: 'Frazer Town', label: 'Frazer Town' },
  { value: 'Gangondanahalli', label: 'Gangondanahalli' },
  { value: 'Goraguntepalya', label: 'Goraguntepalya' },
  { value: 'Guttahalli', label: 'Guttahalli' },
  { value: 'Halasuru', label: 'Halasuru' },
  { value: 'Hirandahalli', label: 'Hirandahalli' },
  { value: 'Hoskote', label: 'Hoskote' },
  { value: 'Hoysala Nagar', label: 'Hoysala Nagar' },
  { value: 'Indiranagar', label: 'Indiranagar' },
  { value: 'Langford Town', label: 'Langford Town' },
  { value: 'Lavelle Road', label: 'Lavelle Road' },
  { value: 'Magadi Road', label: 'Magadi Road' },
  { value: 'Mahanagarapalike', label: 'Mahanagarapalike' },
  { value: 'Malleswaram', label: 'Malleswaram' },
  { value: 'Muthyalanagar', label: 'Muthyalanagar' },
  { value: 'Nagondanahalli', label: 'Nagondanahalli' },
  { value: 'Padarayanapura', label: 'Padarayanapura' },
  { value: 'Ramachandrapura', label: 'Ramachandrapura' },
  { value: 'Richmond Town', label: 'Richmond Town' },
  { value: 'Sahakara Nagar', label: 'Sahakara Nagar' },
  { value: 'Shantinagar', label: 'Shantinagar' },
  { value: 'Srinivasanagar', label: 'Srinivasanagar' },
  { value: 'Tigada', label: 'Tigada' },
  { value: 'Varthur Hobli', label: 'Varthur Hobli' },
  { value: 'Vasanth Nagar', label: 'Vasanth Nagar' },
  { value: 'Welworth City', label: 'Welworth City' },
  // Newly added
  { value: 'Belgaum', label: 'Belgaum' },
  { value: 'Raichur', label: 'Raichur' },
  { value: 'Dharwad', label: 'Dharwad' },
  { value: 'Hubli', label: 'Hubli' },
  { value: 'Davangere', label: 'Davangere' },
]
