export const NAV_LINKS = [
  {
    name: 'Home',
    url: '/',
  },
  // {
  //   name: 'Properties',
  //   url: '/properties',
  // },
  // {
  //   name: 'About Us',
  //   url: '/about',
  // },
  // {
  //   name: 'Careers',
  //   url: '/careers',
  // },
]

export const PROPERTY_TYPES = [
  {
    label: 'Land',
    value: 'Land',
  },
  {
    label: 'Land And Building',
    value: 'Land And Building',
  },
  {
    label: 'Flat',
    value: 'Flat',
  },
  {
    label: 'House',
    value: 'House',
  },
  {
    label: 'Plot',
    value: 'Plot',
  },
]

export const BANGALORE_AREAS = [
  { value: 'KR Puram', label: 'KR Puram' },
  { value: 'Anekal', label: 'Anekal' },
  { value: 'Begur', label: 'Begur' },
  { value: 'Kamakshipalya', label: 'Kamakshipalya' },
  { value: 'Chikkaballapura', label: 'Chikkaballapura' },
  { value: 'Kengeri', label: 'Kengeri' },
  { value: 'Hanumanthanagar', label: 'Hanumanthanagar' },
  { value: 'Bellandur', label: 'Bellandur' },
  { value: 'CV Raman Nagar', label: 'CV Raman Nagar' },
  { value: 'Hoodi', label: 'Hoodi' },
  { value: 'Mahadevapura', label: 'Mahadevapura' },
  { value: 'Marathahalli', label: 'Marathahalli' },
  { value: 'Varthur', label: 'Varthur' },
  { value: 'Whitefield', label: 'Whitefield' },
  { value: 'Banaswadi', label: 'Banaswadi' },
  { value: 'HBR Layout', label: 'HBR Layout' },
  { value: 'Horamavu', label: 'Horamavu' },
  { value: 'Kalyan Nagar', label: 'Kalyan Nagar' },
  { value: 'Kammanahalli', label: 'Kammanahalli' },
  { value: 'Lingarajapuram', label: 'Lingarajapuram' },
  { value: 'Ramamurthy Nagar', label: 'Ramamurthy Nagar' },
  { value: 'Hebbal', label: 'Hebbal' },
  { value: 'Jalahalli', label: 'Jalahalli' },
  { value: 'Mathikere', label: 'Mathikere' },
  { value: 'Peenya', label: 'Peenya' },
  { value: 'Vidyaranyapura', label: 'Vidyaranyapura' },
  { value: 'Yelahanka', label: 'Yelahanka' },
  { value: 'Yeshwanthpur', label: 'Yeshwanthpur' },
  { value: 'Bommanahalli', label: 'Bommanahalli' },
  { value: 'Bommasandra', label: 'Bommasandra' },
  { value: 'BTM Layout', label: 'BTM Layout' },
  { value: 'Electronic City', label: 'Electronic City' },
  { value: 'HSR Layout', label: 'HSR Layout' },
  { value: 'Koramangala', label: 'Koramangala' },
  { value: 'Madiwala', label: 'Madiwala' },
  { value: 'Banashankari', label: 'Banashankari' },
  { value: 'Basavanagudi', label: 'Basavanagudi' },
  { value: 'Girinagar', label: 'Girinagar' },
  { value: 'JP Nagar', label: 'JP Nagar' },
  { value: 'Jayanagar', label: 'Jayanagar' },
  { value: 'Kumaraswamy Layout', label: 'Kumaraswamy Layout' },
  { value: 'Padmanabhanagar', label: 'Padmanabhanagar' },
  { value: 'Uttarahalli', label: 'Uttarahalli' },
  { value: 'Basaveshwaranagar', label: 'Basaveshwaranagar' },
  { value: 'Kamakshipalya', label: 'Kamakshipalya' },
  { value: 'Mahalakshmi Layout', label: 'Mahalakshmi Layout' },
  { value: 'Nagarbhavi', label: 'Nagarbhavi' },
  { value: 'Nandini Layout', label: 'Nandini Layout' },
  { value: 'Nayandahalli', label: 'Nayandahalli' },
  { value: 'Rajajinagar', label: 'Rajajinagar' },
  { value: 'Dasanapura', label: 'Dasanapura' },
  { value: 'Rajarajeshwari Nagar', label: 'Rajarajeshwari Nagar' },
  { value: 'Vijayanagar', label: 'Vijayanagar' },
  { value: 'Attibele', label: 'Attibele' },
  { value: 'Chandapura', label: 'Chandapura' },
  { value: 'Thavarekere', label: 'Thavarekere' },
  { value: 'Chikkabanavara', label: 'Chikkabanavara' },
  { value: 'Hesaraghatta', label: 'Hesaraghatta' },
  { value: 'Jigani', label: 'Jigani' },
  { value: 'Nelamangala', label: 'Nelamangala' },
  { value: 'Sarjapura', label: 'Sarjapura' },
  // Missing areas added:
  { value: 'Bagalur', label: 'Bagalur' },
  { value: 'Bannerghatta', label: 'Bannerghatta' },
  { value: 'Belagavi', label: 'Belagavi' },
  { value: 'Bidarahalli', label: 'Bidarahalli' },
  { value: 'Cooke Town', label: 'Cooke Town' },
  { value: 'Cunningham Road', label: 'Cunningham Road' },
  { value: 'Devanahalli', label: 'Devanahalli' },
  { value: 'Doddanekundi', label: 'Doddanekundi' },
  { value: 'Doddaballapura', label: 'Doddaballapura' },
  { value: 'Frazer Town', label: 'Frazer Town' },
  { value: 'Gangondanahalli', label: 'Gangondanahalli' },
  { value: 'Goraguntepalya', label: 'Goraguntepalya' },
  { value: 'Guttahalli', label: 'Guttahalli' },
  { value: 'Halasuru', label: 'Halasuru' },
  { value: 'Hirandahalli', label: 'Hirandahalli' },
  { value: 'Hoskote', label: 'Hoskote' },
  { value: 'Hoysala Nagar', label: 'Hoysala Nagar' },
  { value: 'Indiranagar', label: 'Indiranagar' },
  { value: 'Langford Town', label: 'Langford Town' },
  { value: 'Lavelle Road', label: 'Lavelle Road' },
  { value: 'Magadi Road', label: 'Magadi Road' },
  { value: 'Mahanagarapalike', label: 'Mahanagarapalike' },
  { value: 'Malleswaram', label: 'Malleswaram' },
  { value: 'Muthyalanagar', label: 'Muthyalanagar' },
  { value: 'Nagondanahalli', label: 'Nagondanahalli' },
  { value: 'Padarayanapura', label: 'Padarayanapura' },
  { value: 'Ramachandrapura', label: 'Ramachandrapura' },
  { value: 'Richmond Town', label: 'Richmond Town' },
  { value: 'Sahakara Nagar', label: 'Sahakara Nagar' },
  { value: 'Shantinagar', label: 'Shantinagar' },
  { value: 'Srinivasanagar', label: 'Srinivasanagar' },
  { value: 'Tigada', label: 'Tigada' },
  { value: 'Varthur Hobli', label: 'Varthur Hobli' },
  { value: 'Vasanth Nagar', label: 'Vasanth Nagar' },
  { value: 'Welworth City', label: 'Welworth City' },
]
